import './globals.css';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const header = (
  <header>
    {/* <Image
      src="../data.jpg"
      alt="Vercel Logo"
      width={572}
      height={20}
      className="mx-auto"
    /> */}
    <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
      <Link href="/">
        <h1 className="text-2xl mt-4 font-bold text-white">Hi, I'm Jenny</h1>
      </Link>
      <p className="text-slate-300">✌ Welcome to my space! ✌</p>
    </div>
  </header>
);

const footer = (
  <footer>
    <div className="text-center text-slate-400 border-t border-slate-500 py-6 mt-12 my-12">
      <br />
      <p>Developed by Jenny</p>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
