import './globals.css';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const header = (
  <header>
    <div>
      <Link href="/">
        <h1>Jenny's Blog</h1>
      </Link>
      <p>✌ Welcome to my tech blog! ✌</p>
      <br />
    </div>
  </header>
);

const footer = (
  <footer>
    <div>
      <br />
      <p>Developed by Jenny</p>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
